# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
permalink:           pretty

# Setup
title:               John Ramey
tagline:             'Statistics and Machine Learning'
description:         'The personal site of <a href="http://ramhiser.com">John Ramey</a> to discuss statistics, machine learning, and other endeavors.'
url:                 http://ramhiser.com
baseurl:             /
paginate:            5
permalink:           ":year/:month/:day/:title/"

# About/contact
author:
  name:              John Ramey
  url:               https://twitter.com/ramhiser
  email:             johnramey@gmail.com

# Custom vars
version:             1.0.0

# Plugins
plugins: [jekyll-paginate, jekyll-gist]

# Google services
google_analytics: UA-33406921-1
